//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.11.26 at 01:56:42 AM PST
//

package com.sciul.recurly.model;

/**
 * @author Gaurav
 */
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="adjustments">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="billing_info">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="invoices">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="redemption">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="subscriptions">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="transactions">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vat_number">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tax_exempt">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="address">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="address2">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="phone">
 *                               &lt;complexType>
 *                                 &lt;simpleContent>
 *                                   &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                                     &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                   &lt;/extension>
 *                                 &lt;/simpleContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="accept_language">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="hosted_login_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="created_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "account" })
@XmlRootElement(name = "accounts")
public class Accounts {

  @XmlElement(required = true)
  protected Accounts.Account account;
  @XmlAttribute(name = "type")
  protected String type;

  /**
   * Gets the value of the account property.
   * 
   * @return possible object is {@link Accounts.Account }
   * 
   */
  public Accounts.Account getAccount() {
    return account;
  }

  /**
   * Sets the value of the account property.
   * 
   * @param value
   *          allowed object is {@link Accounts.Account }
   * 
   */
  public void setAccount(Accounts.Account value) {
    this.account = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="adjustments">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="billing_info">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="invoices">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="redemption">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="subscriptions">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="transactions">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="username">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="vat_number">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="tax_exempt">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="address">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="address2">
   *                     &lt;complexType>
   *                       &lt;simpleContent>
   *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                         &lt;/extension>
   *                       &lt;/simpleContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}int"/>
   *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="phone">
   *                     &lt;complexType>
   *                       &lt;simpleContent>
   *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                         &lt;/extension>
   *                       &lt;/simpleContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="accept_language">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="hosted_login_token" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="created_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "adjustments", "billingInfo", "invoices", "redemption", "subscriptions",
      "transactions", "accountCode", "state", "username", "email", "firstName", "lastName", "companyName", "vatNumber",
      "taxExempt", "address", "acceptLanguage", "hostedLoginToken", "createdAt" })
  public static class Account {

    @XmlElement(required = true)
    protected Accounts.Account.Adjustments adjustments;
    @XmlElement(name = "billing_info", required = true)
    protected Accounts.Account.BillingInfo billingInfo;
    @XmlElement(required = true)
    protected Accounts.Account.Invoices invoices;
    @XmlElement(required = true)
    protected Accounts.Account.Redemption redemption;
    @XmlElement(required = true)
    protected Accounts.Account.Subscriptions subscriptions;
    @XmlElement(required = true)
    protected Accounts.Account.Transactions transactions;
    @XmlElement(name = "account_code")
    protected byte accountCode;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(required = true)
    protected Accounts.Account.Username username;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(name = "first_name", required = true)
    protected String firstName;
    @XmlElement(name = "last_name", required = true)
    protected String lastName;
    @XmlElement(name = "company_name", required = true)
    protected String companyName;
    @XmlElement(name = "vat_number", required = true)
    protected Accounts.Account.VatNumber vatNumber;
    @XmlElement(name = "tax_exempt", required = true)
    protected Accounts.Account.TaxExempt taxExempt;
    @XmlElement(required = true)
    protected Accounts.Account.Address address;
    @XmlElement(name = "accept_language", required = true)
    protected Accounts.Account.AcceptLanguage acceptLanguage;
    @XmlElement(name = "hosted_login_token", required = true)
    protected String hostedLoginToken;
    @XmlElement(name = "created_at", required = true)
    protected Accounts.Account.CreatedAt createdAt;
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * Gets the value of the adjustments property.
     * 
     * @return possible object is {@link Accounts.Account.Adjustments }
     * 
     */
    public Accounts.Account.Adjustments getAdjustments() {
      return adjustments;
    }

    /**
     * Sets the value of the adjustments property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Adjustments }
     * 
     */
    public void setAdjustments(Accounts.Account.Adjustments value) {
      this.adjustments = value;
    }

    /**
     * Gets the value of the billingInfo property.
     * 
     * @return possible object is {@link Accounts.Account.BillingInfo }
     * 
     */
    public Accounts.Account.BillingInfo getBillingInfo() {
      return billingInfo;
    }

    /**
     * Sets the value of the billingInfo property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.BillingInfo }
     * 
     */
    public void setBillingInfo(Accounts.Account.BillingInfo value) {
      this.billingInfo = value;
    }

    /**
     * Gets the value of the invoices property.
     * 
     * @return possible object is {@link Accounts.Account.Invoices }
     * 
     */
    public Accounts.Account.Invoices getInvoices() {
      return invoices;
    }

    /**
     * Sets the value of the invoices property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Invoices }
     * 
     */
    public void setInvoices(Accounts.Account.Invoices value) {
      this.invoices = value;
    }

    /**
     * Gets the value of the redemption property.
     * 
     * @return possible object is {@link Accounts.Account.Redemption }
     * 
     */
    public Accounts.Account.Redemption getRedemption() {
      return redemption;
    }

    /**
     * Sets the value of the redemption property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Redemption }
     * 
     */
    public void setRedemption(Accounts.Account.Redemption value) {
      this.redemption = value;
    }

    /**
     * Gets the value of the subscriptions property.
     * 
     * @return possible object is {@link Accounts.Account.Subscriptions }
     * 
     */
    public Accounts.Account.Subscriptions getSubscriptions() {
      return subscriptions;
    }

    /**
     * Sets the value of the subscriptions property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Subscriptions }
     * 
     */
    public void setSubscriptions(Accounts.Account.Subscriptions value) {
      this.subscriptions = value;
    }

    /**
     * Gets the value of the transactions property.
     * 
     * @return possible object is {@link Accounts.Account.Transactions }
     * 
     */
    public Accounts.Account.Transactions getTransactions() {
      return transactions;
    }

    /**
     * Sets the value of the transactions property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Transactions }
     * 
     */
    public void setTransactions(Accounts.Account.Transactions value) {
      this.transactions = value;
    }

    /**
     * Gets the value of the accountCode property.
     * 
     */
    public byte getAccountCode() {
      return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     */
    public void setAccountCode(byte value) {
      this.accountCode = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
      return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setState(String value) {
      this.state = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return possible object is {@link Accounts.Account.Username }
     * 
     */
    public Accounts.Account.Username getUsername() {
      return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Username }
     * 
     */
    public void setUsername(Accounts.Account.Username value) {
      this.username = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmail() {
      return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setEmail(String value) {
      this.email = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstName() {
      return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setFirstName(String value) {
      this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastName() {
      return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setLastName(String value) {
      this.lastName = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompanyName() {
      return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCompanyName(String value) {
      this.companyName = value;
    }

    /**
     * Gets the value of the vatNumber property.
     * 
     * @return possible object is {@link Accounts.Account.VatNumber }
     * 
     */
    public Accounts.Account.VatNumber getVatNumber() {
      return vatNumber;
    }

    /**
     * Sets the value of the vatNumber property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.VatNumber }
     * 
     */
    public void setVatNumber(Accounts.Account.VatNumber value) {
      this.vatNumber = value;
    }

    /**
     * Gets the value of the taxExempt property.
     * 
     * @return possible object is {@link Accounts.Account.TaxExempt }
     * 
     */
    public Accounts.Account.TaxExempt getTaxExempt() {
      return taxExempt;
    }

    /**
     * Sets the value of the taxExempt property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.TaxExempt }
     * 
     */
    public void setTaxExempt(Accounts.Account.TaxExempt value) {
      this.taxExempt = value;
    }

    /**
     * Gets the value of the address property.
     * 
     * @return possible object is {@link Accounts.Account.Address }
     * 
     */
    public Accounts.Account.Address getAddress() {
      return address;
    }

    /**
     * Sets the value of the address property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.Address }
     * 
     */
    public void setAddress(Accounts.Account.Address value) {
      this.address = value;
    }

    /**
     * Gets the value of the acceptLanguage property.
     * 
     * @return possible object is {@link Accounts.Account.AcceptLanguage }
     * 
     */
    public Accounts.Account.AcceptLanguage getAcceptLanguage() {
      return acceptLanguage;
    }

    /**
     * Sets the value of the acceptLanguage property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.AcceptLanguage }
     * 
     */
    public void setAcceptLanguage(Accounts.Account.AcceptLanguage value) {
      this.acceptLanguage = value;
    }

    /**
     * Gets the value of the hostedLoginToken property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHostedLoginToken() {
      return hostedLoginToken;
    }

    /**
     * Sets the value of the hostedLoginToken property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setHostedLoginToken(String value) {
      this.hostedLoginToken = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return possible object is {@link Accounts.Account.CreatedAt }
     * 
     */
    public Accounts.Account.CreatedAt getCreatedAt() {
      return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *          allowed object is {@link Accounts.Account.CreatedAt }
     * 
     */
    public void setCreatedAt(Accounts.Account.CreatedAt value) {
      this.createdAt = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHref() {
      return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setHref(String value) {
      this.href = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class AcceptLanguage {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "nil")
      protected String nil;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the nil property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getNil() {
        return nil;
      }

      /**
       * Sets the value of the nil property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setNil(String value) {
        this.nil = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="address2">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="phone">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "address1", "address2", "city", "state", "zip", "country", "phone" })
    public static class Address {

      @XmlElement(required = true)
      protected String address1;
      @XmlElement(required = true)
      protected Accounts.Account.Address.Address2 address2;
      @XmlElement(required = true)
      protected String city;
      @XmlElement(required = true)
      protected String state;
      protected int zip;
      @XmlElement(required = true)
      protected String country;
      @XmlElement(required = true)
      protected Accounts.Account.Address.Phone phone;

      /**
       * Gets the value of the address1 property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getAddress1() {
        return address1;
      }

      /**
       * Sets the value of the address1 property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setAddress1(String value) {
        this.address1 = value;
      }

      /**
       * Gets the value of the address2 property.
       * 
       * @return possible object is {@link Accounts.Account.Address.Address2 }
       * 
       */
      public Accounts.Account.Address.Address2 getAddress2() {
        return address2;
      }

      /**
       * Sets the value of the address2 property.
       * 
       * @param value
       *          allowed object is {@link Accounts.Account.Address.Address2 }
       * 
       */
      public void setAddress2(Accounts.Account.Address.Address2 value) {
        this.address2 = value;
      }

      /**
       * Gets the value of the city property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getCity() {
        return city;
      }

      /**
       * Sets the value of the city property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setCity(String value) {
        this.city = value;
      }

      /**
       * Gets the value of the state property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getState() {
        return state;
      }

      /**
       * Sets the value of the state property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setState(String value) {
        this.state = value;
      }

      /**
       * Gets the value of the zip property.
       * 
       */
      public int getZip() {
        return zip;
      }

      /**
       * Sets the value of the zip property.
       * 
       */
      public void setZip(int value) {
        this.zip = value;
      }

      /**
       * Gets the value of the country property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getCountry() {
        return country;
      }

      /**
       * Sets the value of the country property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setCountry(String value) {
        this.country = value;
      }

      /**
       * Gets the value of the phone property.
       * 
       * @return possible object is {@link Accounts.Account.Address.Phone }
       * 
       */
      public Accounts.Account.Address.Phone getPhone() {
        return phone;
      }

      /**
       * Sets the value of the phone property.
       * 
       * @param value
       *          allowed object is {@link Accounts.Account.Address.Phone }
       * 
       */
      public void setPhone(Accounts.Account.Address.Phone value) {
        this.phone = value;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;simpleContent>
       *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/extension>
       *   &lt;/simpleContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "value" })
      public static class Address2 {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "nil")
        protected String nil;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
          return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
          this.value = value;
        }

        /**
         * Gets the value of the nil property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getNil() {
          return nil;
        }

        /**
         * Sets the value of the nil property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setNil(String value) {
          this.nil = value;
        }

      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;simpleContent>
       *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
       *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
       *     &lt;/extension>
       *   &lt;/simpleContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "value" })
      public static class Phone {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "nil")
        protected String nil;

        /**
         * Gets the value of the value property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getValue() {
          return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setValue(String value) {
          this.value = value;
        }

        /**
         * Gets the value of the nil property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getNil() {
          return nil;
        }

        /**
         * Sets the value of the nil property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setNil(String value) {
          this.nil = value;
        }

      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Adjustments {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class BillingInfo {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CreatedAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Invoices {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Redemption {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Subscriptions {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class TaxExempt {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Transactions {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Username {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "nil")
      protected String nil;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the nil property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getNil() {
        return nil;
      }

      /**
       * Sets the value of the nil property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setNil(String value) {
        this.nil = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class VatNumber {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "nil")
      protected String nil;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the nil property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getNil() {
        return nil;
      }

      /**
       * Sets the value of the nil property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setNil(String value) {
        this.nil = value;
      }

    }

  }

}
