//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.21 at 05:16:31 PM PST
//

package com.sciul.recurly.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transaction_error">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="error_category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="merchant_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="customer_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="error">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="transaction">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="tax_in_cents" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="test" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="voidable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="refundable" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="transaction_error">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="error_category" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="merchant_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="customer_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="cvv_result">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="avs_result">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="avs_result_street" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="avs_result_postal" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="created_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="details">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="account">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="billing_info">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="card_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                 &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                                 &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                                 &lt;element name="first_six" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                                 &lt;element name="last_four" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                               &lt;/sequence>
 *                                               &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "transactionError", "error", "transaction" })
@XmlRootElement(name = "errors")
public class Errors {

  @XmlElement(name = "transaction_error", required = true)
  protected Errors.TransactionError transactionError;
  @XmlElement(required = true)
  protected Errors.Error error;
  @XmlElement(required = true)
  protected Errors.Transaction transaction;

  /**
   * Gets the value of the transactionError property.
   * 
   * @return possible object is {@link Errors.TransactionError }
   * 
   */
  public Errors.TransactionError getTransactionError() {
    return transactionError;
  }

  /**
   * Sets the value of the transactionError property.
   * 
   * @param value
   *          allowed object is {@link Errors.TransactionError }
   * 
   */
  public void setTransactionError(Errors.TransactionError value) {
    this.transactionError = value;
  }

  /**
   * Gets the value of the error property.
   * 
   * @return possible object is {@link Errors.Error }
   * 
   */
  public Errors.Error getError() {
    return error;
  }

  /**
   * Sets the value of the error property.
   * 
   * @param value
   *          allowed object is {@link Errors.Error }
   * 
   */
  public void setError(Errors.Error value) {
    this.error = value;
  }

  /**
   * Gets the value of the transaction property.
   * 
   * @return possible object is {@link Errors.Transaction }
   * 
   */
  public Errors.Transaction getTransaction() {
    return transaction;
  }

  /**
   * Sets the value of the transaction property.
   * 
   * @param value
   *          allowed object is {@link Errors.Transaction }
   * 
   */
  public void setTransaction(Errors.Transaction value) {
    this.transaction = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;simpleContent>
   *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *       &lt;attribute name="field" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="symbol" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/extension>
   *   &lt;/simpleContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "value" })
  public static class Error {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "field")
    protected String field;
    @XmlAttribute(name = "symbol")
    protected String symbol;

    /**
     * Gets the value of the value property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getValue() {
      return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setValue(String value) {
      this.value = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getField() {
      return field;
    }

    /**
     * Sets the value of the field property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setField(String value) {
      this.field = value;
    }

    /**
     * Gets the value of the symbol property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSymbol() {
      return symbol;
    }

    /**
     * Sets the value of the symbol property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setSymbol(String value) {
      this.symbol = value;
    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="action" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *         &lt;element name="tax_in_cents" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="test" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="voidable" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="refundable" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="transaction_error">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="error_category" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="merchant_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="customer_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="cvv_result">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="avs_result">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="avs_result_street" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="avs_result_postal" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="created_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="details">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="account">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *                             &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="billing_info">
   *                               &lt;complexType>
   *                                 &lt;complexContent>
   *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                                     &lt;sequence>
   *                                       &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="card_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                                       &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *                                       &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *                                       &lt;element name="first_six" type="{http://www.w3.org/2001/XMLSchema}int"/>
   *                                       &lt;element name="last_four" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *                                     &lt;/sequence>
   *                                     &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                                   &lt;/restriction>
   *                                 &lt;/complexContent>
   *                               &lt;/complexType>
   *                             &lt;/element>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "uuid", "action", "amountInCents", "taxInCents", "currency", "status", "reference",
      "test", "voidable", "refundable", "transactionError", "cvvResult", "avsResult", "avsResultStreet",
      "avsResultPostal", "createdAt", "details" })
  public static class Transaction {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String action;
    @XmlElement(name = "amount_in_cents")
    protected short amountInCents;
    @XmlElement(name = "tax_in_cents")
    protected byte taxInCents;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String reference;
    @XmlElement(required = true)
    protected String test;
    @XmlElement(required = true)
    protected String voidable;
    @XmlElement(required = true)
    protected String refundable;
    @XmlElement(name = "transaction_error", required = true)
    protected Errors.Transaction.TransactionError transactionError;
    @XmlElement(name = "cvv_result", required = true)
    protected Errors.Transaction.CvvResult cvvResult;
    @XmlElement(name = "avs_result", required = true)
    protected Errors.Transaction.AvsResult avsResult;
    @XmlElement(name = "avs_result_street", required = true)
    protected String avsResultStreet;
    @XmlElement(name = "avs_result_postal", required = true)
    protected String avsResultPostal;
    @XmlElement(name = "created_at", required = true)
    protected Errors.Transaction.CreatedAt createdAt;
    @XmlElement(required = true)
    protected Errors.Transaction.Details details;
    @XmlAttribute(name = "href")
    protected String href;
    @XmlAttribute(name = "type")
    protected String type;

    /**
     * Gets the value of the uuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUuid() {
      return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setUuid(String value) {
      this.uuid = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAction() {
      return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setAction(String value) {
      this.action = value;
    }

    /**
     * Gets the value of the amountInCents property.
     * 
     */
    public short getAmountInCents() {
      return amountInCents;
    }

    /**
     * Sets the value of the amountInCents property.
     * 
     */
    public void setAmountInCents(short value) {
      this.amountInCents = value;
    }

    /**
     * Gets the value of the taxInCents property.
     * 
     */
    public byte getTaxInCents() {
      return taxInCents;
    }

    /**
     * Sets the value of the taxInCents property.
     * 
     */
    public void setTaxInCents(byte value) {
      this.taxInCents = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
      return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
      this.currency = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getStatus() {
      return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setStatus(String value) {
      this.status = value;
    }

    /**
     * Gets the value of the reference property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getReference() {
      return reference;
    }

    /**
     * Sets the value of the reference property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setReference(String value) {
      this.reference = value;
    }

    /**
     * Gets the value of the test property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTest() {
      return test;
    }

    /**
     * Sets the value of the test property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setTest(String value) {
      this.test = value;
    }

    /**
     * Gets the value of the voidable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVoidable() {
      return voidable;
    }

    /**
     * Sets the value of the voidable property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setVoidable(String value) {
      this.voidable = value;
    }

    /**
     * Gets the value of the refundable property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getRefundable() {
      return refundable;
    }

    /**
     * Sets the value of the refundable property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setRefundable(String value) {
      this.refundable = value;
    }

    /**
     * Gets the value of the transactionError property.
     * 
     * @return possible object is {@link Errors.Transaction.TransactionError }
     * 
     */
    public Errors.Transaction.TransactionError getTransactionError() {
      return transactionError;
    }

    /**
     * Sets the value of the transactionError property.
     * 
     * @param value
     *          allowed object is {@link Errors.Transaction.TransactionError }
     * 
     */
    public void setTransactionError(Errors.Transaction.TransactionError value) {
      this.transactionError = value;
    }

    /**
     * Gets the value of the cvvResult property.
     * 
     * @return possible object is {@link Errors.Transaction.CvvResult }
     * 
     */
    public Errors.Transaction.CvvResult getCvvResult() {
      return cvvResult;
    }

    /**
     * Sets the value of the cvvResult property.
     * 
     * @param value
     *          allowed object is {@link Errors.Transaction.CvvResult }
     * 
     */
    public void setCvvResult(Errors.Transaction.CvvResult value) {
      this.cvvResult = value;
    }

    /**
     * Gets the value of the avsResult property.
     * 
     * @return possible object is {@link Errors.Transaction.AvsResult }
     * 
     */
    public Errors.Transaction.AvsResult getAvsResult() {
      return avsResult;
    }

    /**
     * Sets the value of the avsResult property.
     * 
     * @param value
     *          allowed object is {@link Errors.Transaction.AvsResult }
     * 
     */
    public void setAvsResult(Errors.Transaction.AvsResult value) {
      this.avsResult = value;
    }

    /**
     * Gets the value of the avsResultStreet property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAvsResultStreet() {
      return avsResultStreet;
    }

    /**
     * Sets the value of the avsResultStreet property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setAvsResultStreet(String value) {
      this.avsResultStreet = value;
    }

    /**
     * Gets the value of the avsResultPostal property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getAvsResultPostal() {
      return avsResultPostal;
    }

    /**
     * Sets the value of the avsResultPostal property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setAvsResultPostal(String value) {
      this.avsResultPostal = value;
    }

    /**
     * Gets the value of the createdAt property.
     * 
     * @return possible object is {@link Errors.Transaction.CreatedAt }
     * 
     */
    public Errors.Transaction.CreatedAt getCreatedAt() {
      return createdAt;
    }

    /**
     * Sets the value of the createdAt property.
     * 
     * @param value
     *          allowed object is {@link Errors.Transaction.CreatedAt }
     * 
     */
    public void setCreatedAt(Errors.Transaction.CreatedAt value) {
      this.createdAt = value;
    }

    /**
     * Gets the value of the details property.
     * 
     * @return possible object is {@link Errors.Transaction.Details }
     * 
     */
    public Errors.Transaction.Details getDetails() {
      return details;
    }

    /**
     * Sets the value of the details property.
     * 
     * @param value
     *          allowed object is {@link Errors.Transaction.Details }
     * 
     */
    public void setDetails(Errors.Transaction.Details value) {
      this.details = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHref() {
      return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setHref(String value) {
      this.href = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getType() {
      return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setType(String value) {
      this.type = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class AvsResult {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "code")
      protected String code;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the code property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getCode() {
        return code;
      }

      /**
       * Sets the value of the code property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setCode(String value) {
        this.code = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CreatedAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="code" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CvvResult {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "code")
      protected String code;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the code property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getCode() {
        return code;
      }

      /**
       * Sets the value of the code property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setCode(String value) {
        this.code = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="account">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="billing_info">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="card_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="first_six" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="last_four" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "account" })
    public static class Details {

      @XmlElement(required = true)
      protected Errors.Transaction.Details.Account account;

      /**
       * Gets the value of the account property.
       * 
       * @return possible object is {@link Errors.Transaction.Details.Account }
       * 
       */
      public Errors.Transaction.Details.Account getAccount() {
        return account;
      }

      /**
       * Sets the value of the account property.
       * 
       * @param value
       *          allowed object is {@link Errors.Transaction.Details.Account }
       * 
       */
      public void setAccount(Errors.Transaction.Details.Account value) {
        this.account = value;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}byte"/>
       *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="company" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="billing_info">
       *           &lt;complexType>
       *             &lt;complexContent>
       *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *                 &lt;sequence>
       *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="card_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *                   &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
       *                   &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
       *                   &lt;element name="first_six" type="{http://www.w3.org/2001/XMLSchema}int"/>
       *                   &lt;element name="last_four" type="{http://www.w3.org/2001/XMLSchema}byte"/>
       *                 &lt;/sequence>
       *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
       *               &lt;/restriction>
       *             &lt;/complexContent>
       *           &lt;/complexType>
       *         &lt;/element>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "accountCode", "firstName", "lastName", "company", "email", "billingInfo" })
      public static class Account {

        @XmlElement(name = "account_code")
        protected byte accountCode;
        @XmlElement(name = "first_name", required = true)
        protected String firstName;
        @XmlElement(name = "last_name", required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String company;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(name = "billing_info", required = true)
        protected Errors.Transaction.Details.Account.BillingInfo billingInfo;

        /**
         * Gets the value of the accountCode property.
         * 
         */
        public byte getAccountCode() {
          return accountCode;
        }

        /**
         * Sets the value of the accountCode property.
         * 
         */
        public void setAccountCode(byte value) {
          this.accountCode = value;
        }

        /**
         * Gets the value of the firstName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getFirstName() {
          return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setFirstName(String value) {
          this.firstName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getLastName() {
          return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setLastName(String value) {
          this.lastName = value;
        }

        /**
         * Gets the value of the company property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getCompany() {
          return company;
        }

        /**
         * Sets the value of the company property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setCompany(String value) {
          this.company = value;
        }

        /**
         * Gets the value of the email property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getEmail() {
          return email;
        }

        /**
         * Sets the value of the email property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setEmail(String value) {
          this.email = value;
        }

        /**
         * Gets the value of the billingInfo property.
         * 
         * @return possible object is {@link Errors.Transaction.Details.Account.BillingInfo }
         * 
         */
        public Errors.Transaction.Details.Account.BillingInfo getBillingInfo() {
          return billingInfo;
        }

        /**
         * Sets the value of the billingInfo property.
         * 
         * @param value
         *          allowed object is {@link Errors.Transaction.Details.Account.BillingInfo }
         * 
         */
        public void setBillingInfo(Errors.Transaction.Details.Account.BillingInfo value) {
          this.billingInfo = value;
        }

        /**
         * <p>
         * Java class for anonymous complex type.
         * 
         * <p>
         * The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="address2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="zip" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="card_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *         &lt;element name="month" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *         &lt;element name="first_six" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="last_four" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *       &lt;/sequence>
         *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "firstName", "lastName", "address1", "address2", "city", "state", "zip",
            "country", "phone", "vatNumber", "cardType", "year", "month", "firstSix", "lastFour" })
        public static class BillingInfo {

          @XmlElement(name = "first_name", required = true)
          protected String firstName;
          @XmlElement(name = "last_name", required = true)
          protected String lastName;
          @XmlElement(required = true)
          protected String address1;
          @XmlElement(required = true)
          protected String address2;
          @XmlElement(required = true)
          protected String city;
          @XmlElement(required = true)
          protected String state;
          @XmlElement(required = true)
          protected String zip;
          @XmlElement(required = true)
          protected String country;
          @XmlElement(required = true)
          protected String phone;
          @XmlElement(name = "vat_number", required = true)
          protected String vatNumber;
          @XmlElement(name = "card_type", required = true)
          protected String cardType;
          protected short year;
          protected byte month;
          @XmlElement(name = "first_six")
          protected int firstSix;
          @XmlElement(name = "last_four")
          protected byte lastFour;
          @XmlAttribute(name = "type")
          protected String type;

          /**
           * Gets the value of the firstName property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getFirstName() {
            return firstName;
          }

          /**
           * Sets the value of the firstName property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setFirstName(String value) {
            this.firstName = value;
          }

          /**
           * Gets the value of the lastName property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getLastName() {
            return lastName;
          }

          /**
           * Sets the value of the lastName property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setLastName(String value) {
            this.lastName = value;
          }

          /**
           * Gets the value of the address1 property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getAddress1() {
            return address1;
          }

          /**
           * Sets the value of the address1 property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setAddress1(String value) {
            this.address1 = value;
          }

          /**
           * Gets the value of the address2 property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getAddress2() {
            return address2;
          }

          /**
           * Sets the value of the address2 property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setAddress2(String value) {
            this.address2 = value;
          }

          /**
           * Gets the value of the city property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getCity() {
            return city;
          }

          /**
           * Sets the value of the city property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setCity(String value) {
            this.city = value;
          }

          /**
           * Gets the value of the state property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getState() {
            return state;
          }

          /**
           * Sets the value of the state property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setState(String value) {
            this.state = value;
          }

          /**
           * Gets the value of the zip property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getZip() {
            return zip;
          }

          /**
           * Sets the value of the zip property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setZip(String value) {
            this.zip = value;
          }

          /**
           * Gets the value of the country property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getCountry() {
            return country;
          }

          /**
           * Sets the value of the country property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setCountry(String value) {
            this.country = value;
          }

          /**
           * Gets the value of the phone property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getPhone() {
            return phone;
          }

          /**
           * Sets the value of the phone property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setPhone(String value) {
            this.phone = value;
          }

          /**
           * Gets the value of the vatNumber property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getVatNumber() {
            return vatNumber;
          }

          /**
           * Sets the value of the vatNumber property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setVatNumber(String value) {
            this.vatNumber = value;
          }

          /**
           * Gets the value of the cardType property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getCardType() {
            return cardType;
          }

          /**
           * Sets the value of the cardType property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setCardType(String value) {
            this.cardType = value;
          }

          /**
           * Gets the value of the year property.
           * 
           */
          public short getYear() {
            return year;
          }

          /**
           * Sets the value of the year property.
           * 
           */
          public void setYear(short value) {
            this.year = value;
          }

          /**
           * Gets the value of the month property.
           * 
           */
          public byte getMonth() {
            return month;
          }

          /**
           * Sets the value of the month property.
           * 
           */
          public void setMonth(byte value) {
            this.month = value;
          }

          /**
           * Gets the value of the firstSix property.
           * 
           */
          public int getFirstSix() {
            return firstSix;
          }

          /**
           * Sets the value of the firstSix property.
           * 
           */
          public void setFirstSix(int value) {
            this.firstSix = value;
          }

          /**
           * Gets the value of the lastFour property.
           * 
           */
          public byte getLastFour() {
            return lastFour;
          }

          /**
           * Sets the value of the lastFour property.
           * 
           */
          public void setLastFour(byte value) {
            this.lastFour = value;
          }

          /**
           * Gets the value of the type property.
           * 
           * @return possible object is {@link String }
           * 
           */
          public String getType() {
            return type;
          }

          /**
           * Sets the value of the type property.
           * 
           * @param value
           *          allowed object is {@link String }
           * 
           */
          public void setType(String value) {
            this.type = value;
          }

        }

      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="error_category" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="merchant_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="customer_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "errorCode", "errorCategory", "merchantMessage", "customerMessage" })
    public static class TransactionError {

      @XmlElement(name = "error_code", required = true)
      protected String errorCode;
      @XmlElement(name = "error_category", required = true)
      protected String errorCategory;
      @XmlElement(name = "merchant_message", required = true)
      protected String merchantMessage;
      @XmlElement(name = "customer_message", required = true)
      protected String customerMessage;

      /**
       * Gets the value of the errorCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getErrorCode() {
        return errorCode;
      }

      /**
       * Sets the value of the errorCode property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setErrorCode(String value) {
        this.errorCode = value;
      }

      /**
       * Gets the value of the errorCategory property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getErrorCategory() {
        return errorCategory;
      }

      /**
       * Sets the value of the errorCategory property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setErrorCategory(String value) {
        this.errorCategory = value;
      }

      /**
       * Gets the value of the merchantMessage property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getMerchantMessage() {
        return merchantMessage;
      }

      /**
       * Sets the value of the merchantMessage property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setMerchantMessage(String value) {
        this.merchantMessage = value;
      }

      /**
       * Gets the value of the customerMessage property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getCustomerMessage() {
        return customerMessage;
      }

      /**
       * Sets the value of the customerMessage property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setCustomerMessage(String value) {
        this.customerMessage = value;
      }

    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="error_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="error_category" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="merchant_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="customer_message" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "errorCode", "errorCategory", "merchantMessage", "customerMessage" })
  public static class TransactionError {

    @XmlElement(name = "error_code", required = true)
    protected String errorCode;
    @XmlElement(name = "error_category", required = true)
    protected String errorCategory;
    @XmlElement(name = "merchant_message", required = true)
    protected String merchantMessage;
    @XmlElement(name = "customer_message", required = true)
    protected String customerMessage;

    /**
     * Gets the value of the errorCode property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getErrorCode() {
      return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setErrorCode(String value) {
      this.errorCode = value;
    }

    /**
     * Gets the value of the errorCategory property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getErrorCategory() {
      return errorCategory;
    }

    /**
     * Sets the value of the errorCategory property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setErrorCategory(String value) {
      this.errorCategory = value;
    }

    /**
     * Gets the value of the merchantMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getMerchantMessage() {
      return merchantMessage;
    }

    /**
     * Sets the value of the merchantMessage property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setMerchantMessage(String value) {
      this.merchantMessage = value;
    }

    /**
     * Gets the value of the customerMessage property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCustomerMessage() {
      return customerMessage;
    }

    /**
     * Sets the value of the customerMessage property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCustomerMessage(String value) {
      this.customerMessage = value;
    }

  }

}
