//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.21 at 05:16:31 PM PST
//

package com.sciul.recurly.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "transactionError", "error", "transaction" })
@XmlRootElement(name = "errors")
public class Errors {

  @XmlElement(name = "transaction_error", required = true)
  protected Errors.TransactionError transactionError;
  @XmlElement(required = true)
  protected Errors.Error error;
  @XmlElement(required = true)
  protected Errors.Transaction transaction;

  
  public Errors.TransactionError getTransactionError() {
    return transactionError;
  }

  
  public void setTransactionError(Errors.TransactionError value) {
    this.transactionError = value;
  }

 
  public Errors.Error getError() {
    return error;
  }

  
  public void setError(Errors.Error value) {
    this.error = value;
  }

  
  public Errors.Transaction getTransaction() {
    return transaction;
  }

  
  public void setTransaction(Errors.Transaction value) {
    this.transaction = value;
  }

  
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "value" })
  public static class Error {

    @XmlValue
    protected String value;
    @XmlAttribute(name = "field")
    protected String field;
    @XmlAttribute(name = "symbol")
    protected String symbol;

   
    public String getValue() {
      return value;
    }

    
    public void setValue(String value) {
      this.value = value;
    }

   
    public String getField() {
      return field;
    }

   
    public void setField(String value) {
      this.field = value;
    }

    
    public String getSymbol() {
      return symbol;
    }

   
    public void setSymbol(String value) {
      this.symbol = value;
    }

  }

  

  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "uuid", "action", "amountInCents", "taxInCents", "currency", "status", "reference",
      "test", "voidable", "refundable", "transactionError", "cvvResult", "avsResult", "avsResultStreet",
      "avsResultPostal", "createdAt", "details" })
  public static class Transaction {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String action;
    @XmlElement(name = "amount_in_cents")
    protected short amountInCents;
    @XmlElement(name = "tax_in_cents")
    protected byte taxInCents;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected String status;
    @XmlElement(required = true)
    protected String reference;
    @XmlElement(required = true)
    protected String test;
    @XmlElement(required = true)
    protected String voidable;
    @XmlElement(required = true)
    protected String refundable;
    @XmlElement(name = "transaction_error", required = true)
    protected Errors.Transaction.TransactionError transactionError;
    @XmlElement(name = "cvv_result", required = true)
    protected Errors.Transaction.CvvResult cvvResult;
    @XmlElement(name = "avs_result", required = true)
    protected Errors.Transaction.AvsResult avsResult;
    @XmlElement(name = "avs_result_street", required = true)
    protected String avsResultStreet;
    @XmlElement(name = "avs_result_postal", required = true)
    protected String avsResultPostal;
    @XmlElement(name = "created_at", required = true)
    protected Errors.Transaction.CreatedAt createdAt;
    @XmlElement(required = true)
    protected Errors.Transaction.Details details;
    @XmlAttribute(name = "href")
    protected String href;
    @XmlAttribute(name = "type")
    protected String type;

   
    public String getUuid() {
      return uuid;
    }

    
    public void setUuid(String value) {
      this.uuid = value;
    }

    

    public String getAction() {
      return action;
    }

    

    public void setAction(String value) {
      this.action = value;
    }

    

    public short getAmountInCents() {
      return amountInCents;
    }

    

    public void setAmountInCents(short value) {
      this.amountInCents = value;
    }

   

    public byte getTaxInCents() {
      return taxInCents;
    }

    
    public void setTaxInCents(byte value) {
      this.taxInCents = value;
    }

   
    public String getCurrency() {
      return currency;
    }

   
    public void setCurrency(String value) {
      this.currency = value;
    }

    
    public String getStatus() {
      return status;
    }

    
    public void setStatus(String value) {
      this.status = value;
    }

   
    public String getReference() {
      return reference;
    }

   
    public void setReference(String value) {
      this.reference = value;
    }

    
    public String getTest() {
      return test;
    }

   
    public void setTest(String value) {
      this.test = value;
    }

   
    public String getVoidable() {
      return voidable;
    }

    
    public void setVoidable(String value) {
      this.voidable = value;
    }

   
    public String getRefundable() {
      return refundable;
    }

    
    public void setRefundable(String value) {
      this.refundable = value;
    }

    
    public Errors.Transaction.TransactionError getTransactionError() {
      return transactionError;
    }

    
    public void setTransactionError(Errors.Transaction.TransactionError value) {
      this.transactionError = value;
    }

   
    public Errors.Transaction.CvvResult getCvvResult() {
      return cvvResult;
    }

    
    public void setCvvResult(Errors.Transaction.CvvResult value) {
      this.cvvResult = value;
    }

    
    public Errors.Transaction.AvsResult getAvsResult() {
      return avsResult;
    }

    
    public void setAvsResult(Errors.Transaction.AvsResult value) {
      this.avsResult = value;
    }

    
    public String getAvsResultStreet() {
      return avsResultStreet;
    }

    
    public void setAvsResultStreet(String value) {
      this.avsResultStreet = value;
    }

    
    public String getAvsResultPostal() {
      return avsResultPostal;
    }

   
    public void setAvsResultPostal(String value) {
      this.avsResultPostal = value;
    }

    
    public Errors.Transaction.CreatedAt getCreatedAt() {
      return createdAt;
    }

    
    public void setCreatedAt(Errors.Transaction.CreatedAt value) {
      this.createdAt = value;
    }

  
    public Errors.Transaction.Details getDetails() {
      return details;
    }

   
    public void setDetails(Errors.Transaction.Details value) {
      this.details = value;
    }

   
    public String getHref() {
      return href;
    }

    
    public void setHref(String value) {
      this.href = value;
    }

    
    public String getType() {
      return type;
    }

    
    public void setType(String value) {
      this.type = value;
    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class AvsResult {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "code")
      protected String code;

      
      public String getValue() {
        return value;
      }

     
      public void setValue(String value) {
        this.value = value;
      }

     
      public String getCode() {
        return code;
      }

      
      public void setCode(String value) {
        this.code = value;
      }

    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CreatedAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

     
      public XMLGregorianCalendar getValue() {
        return value;
      }

      
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      
      public String getType() {
        return type;
      }

     
      public void setType(String value) {
        this.type = value;
      }

    }

    
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CvvResult {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "code")
      protected String code;

      
      public String getValue() {
        return value;
      }

      
      public void setValue(String value) {
        this.value = value;
      }

      
      public String getCode() {
        return code;
      }

      
      public void setCode(String value) {
        this.code = value;
      }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "account" })
    public static class Details {

      @XmlElement(required = true)
      protected Errors.Transaction.Details.Account account;

     
      public Errors.Transaction.Details.Account getAccount() {
        return account;
      }

     
      public void setAccount(Errors.Transaction.Details.Account value) {
        this.account = value;
      }

      
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "accountCode", "firstName", "lastName", "company", "email", "billingInfo" })
      public static class Account {

        @XmlElement(name = "account_code")
        protected byte accountCode;
        @XmlElement(name = "first_name", required = true)
        protected String firstName;
        @XmlElement(name = "last_name", required = true)
        protected String lastName;
        @XmlElement(required = true)
        protected String company;
        @XmlElement(required = true)
        protected String email;
        @XmlElement(name = "billing_info", required = true)
        protected Errors.Transaction.Details.Account.BillingInfo billingInfo;

        
        public byte getAccountCode() {
          return accountCode;
        }

       
        public void setAccountCode(byte value) {
          this.accountCode = value;
        }

       
        public String getFirstName() {
          return firstName;
        }

        
        public void setFirstName(String value) {
          this.firstName = value;
        }

        
        public String getLastName() {
          return lastName;
        }

        
        public void setLastName(String value) {
          this.lastName = value;
        }

       
        public String getCompany() {
          return company;
        }

       
        public void setCompany(String value) {
          this.company = value;
        }

        
        public String getEmail() {
          return email;
        }

       
        public void setEmail(String value) {
          this.email = value;
        }

       
        public Errors.Transaction.Details.Account.BillingInfo getBillingInfo() {
          return billingInfo;
        }

        
        public void setBillingInfo(Errors.Transaction.Details.Account.BillingInfo value) {
          this.billingInfo = value;
        }

       
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = { "firstName", "lastName", "address1", "address2", "city", "state", "zip",
            "country", "phone", "vatNumber", "cardType", "year", "month", "firstSix", "lastFour" })
        public static class BillingInfo {

          @XmlElement(name = "first_name", required = true)
          protected String firstName;
          @XmlElement(name = "last_name", required = true)
          protected String lastName;
          @XmlElement(required = true)
          protected String address1;
          @XmlElement(required = true)
          protected String address2;
          @XmlElement(required = true)
          protected String city;
          @XmlElement(required = true)
          protected String state;
          @XmlElement(required = true)
          protected String zip;
          @XmlElement(required = true)
          protected String country;
          @XmlElement(required = true)
          protected String phone;
          @XmlElement(name = "vat_number", required = true)
          protected String vatNumber;
          @XmlElement(name = "card_type", required = true)
          protected String cardType;
          protected short year;
          protected byte month;
          @XmlElement(name = "first_six")
          protected int firstSix;
          @XmlElement(name = "last_four")
          protected byte lastFour;
          @XmlAttribute(name = "type")
          protected String type;

          
          public String getFirstName() {
            return firstName;
          }

         
          public void setFirstName(String value) {
            this.firstName = value;
          }

         
          public String getLastName() {
            return lastName;
          }

          
          public void setLastName(String value) {
            this.lastName = value;
          }

          
          public String getAddress1() {
            return address1;
          }

          
          public void setAddress1(String value) {
            this.address1 = value;
          }

          
          public String getAddress2() {
            return address2;
          }

          
          public void setAddress2(String value) {
            this.address2 = value;
          }

          
          public String getCity() {
            return city;
          }

          
          public void setCity(String value) {
            this.city = value;
          }

         
          public String getState() {
            return state;
          }

         
          public void setState(String value) {
            this.state = value;
          }

         
          public String getZip() {
            return zip;
          }

         
          public void setZip(String value) {
            this.zip = value;
          }

         
          public String getCountry() {
            return country;
          }

         
          public void setCountry(String value) {
            this.country = value;
          }

          
          public String getPhone() {
            return phone;
          }

          
          public void setPhone(String value) {
            this.phone = value;
          }

          
          public String getVatNumber() {
            return vatNumber;
          }

          
          public void setVatNumber(String value) {
            this.vatNumber = value;
          }

          
          public String getCardType() {
            return cardType;
          }

          
          public void setCardType(String value) {
            this.cardType = value;
          }

          
          public short getYear() {
            return year;
          }

         
          public void setYear(short value) {
            this.year = value;
          }

          
          public byte getMonth() {
            return month;
          }

          
          public void setMonth(byte value) {
            this.month = value;
          }

          public int getFirstSix() {
            return firstSix;
          }

          
          public void setFirstSix(int value) {
            this.firstSix = value;
          }

         
          public byte getLastFour() {
            return lastFour;
          }

         
          public void setLastFour(byte value) {
            this.lastFour = value;
          }

          
          public String getType() {
            return type;
          }

          
          public void setType(String value) {
            this.type = value;
          }

        }

      }

    }

   
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "errorCode", "errorCategory", "merchantMessage", "customerMessage" })
    public static class TransactionError {

      @XmlElement(name = "error_code", required = true)
      protected String errorCode;
      @XmlElement(name = "error_category", required = true)
      protected String errorCategory;
      @XmlElement(name = "merchant_message", required = true)
      protected String merchantMessage;
      @XmlElement(name = "customer_message", required = true)
      protected String customerMessage;

      
      public String getErrorCode() {
        return errorCode;
      }

      
      public void setErrorCode(String value) {
        this.errorCode = value;
      }

      
      public String getErrorCategory() {
        return errorCategory;
      }

      
      public void setErrorCategory(String value) {
        this.errorCategory = value;
      }

      
      public String getMerchantMessage() {
        return merchantMessage;
      }

      
      public void setMerchantMessage(String value) {
        this.merchantMessage = value;
      }

      
      public String getCustomerMessage() {
        return customerMessage;
      }

      
      public void setCustomerMessage(String value) {
        this.customerMessage = value;
      }

    }

  }

 
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "errorCode", "errorCategory", "merchantMessage", "customerMessage" })
  public static class TransactionError {

    @XmlElement(name = "error_code", required = true)
    protected String errorCode;
    @XmlElement(name = "error_category", required = true)
    protected String errorCategory;
    @XmlElement(name = "merchant_message", required = true)
    protected String merchantMessage;
    @XmlElement(name = "customer_message", required = true)
    protected String customerMessage;

    
    public String getErrorCode() {
      return errorCode;
    }

    
    public void setErrorCode(String value) {
      this.errorCode = value;
    }

    
    public String getErrorCategory() {
      return errorCategory;
    }

    
    public void setErrorCategory(String value) {
      this.errorCategory = value;
    }

    
    public String getMerchantMessage() {
      return merchantMessage;
    }

    
    public void setMerchantMessage(String value) {
      this.merchantMessage = value;
    }

    
    public String getCustomerMessage() {
      return customerMessage;
    }

   
    public void setCustomerMessage(String value) {
      this.customerMessage = value;
    }

  }

}
