//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2015.01.02 at 04:09:24 PM PST
//

package com.sciul.recurly.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="account">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="invoice">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="subscription_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="invoice_number" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="po_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="total_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="date">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="closed_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="net_terms" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="collection_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "account", "invoice" })
@XmlRootElement(name = "new_invoice_notification")
public class NewInvoiceNotification {

  @XmlElement(required = true)
  protected NewInvoiceNotification.Account account;
  @XmlElement(required = true)
  protected NewInvoiceNotification.Invoice invoice;

  /**
   * Gets the value of the account property.
   * 
   * @return possible object is {@link NewInvoiceNotification.Account }
   * 
   */
  public NewInvoiceNotification.Account getAccount() {
    return account;
  }

  /**
   * Sets the value of the account property.
   * 
   * @param value
   *          allowed object is {@link NewInvoiceNotification.Account }
   * 
   */
  public void setAccount(NewInvoiceNotification.Account value) {
    this.account = value;
  }

  /**
   * Gets the value of the invoice property.
   * 
   * @return possible object is {@link NewInvoiceNotification.Invoice }
   * 
   */
  public NewInvoiceNotification.Invoice getInvoice() {
    return invoice;
  }

  /**
   * Sets the value of the invoice property.
   * 
   * @param value
   *          allowed object is {@link NewInvoiceNotification.Invoice }
   * 
   */
  public void setInvoice(NewInvoiceNotification.Invoice value) {
    this.invoice = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="account_code" type="{http://www.w3.org/2001/XMLSchema}long"/>
   *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="email" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="first_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="last_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="company_name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "accountCode", "username", "email", "firstName", "lastName", "companyName" })
  public static class Account {

    @XmlElement(name = "account_code")
    protected long accountCode;
    @XmlElement(required = true)
    protected String username;
    @XmlElement(required = true)
    protected String email;
    @XmlElement(name = "first_name", required = true)
    protected String firstName;
    @XmlElement(name = "last_name", required = true)
    protected String lastName;
    @XmlElement(name = "company_name", required = true)
    protected String companyName;

    /**
     * Gets the value of the accountCode property.
     * 
     */
    public long getAccountCode() {
      return accountCode;
    }

    /**
     * Sets the value of the accountCode property.
     * 
     */
    public void setAccountCode(long value) {
      this.accountCode = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUsername() {
      return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setUsername(String value) {
      this.username = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getEmail() {
      return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setEmail(String value) {
      this.email = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getFirstName() {
      return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setFirstName(String value) {
      this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getLastName() {
      return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setLastName(String value) {
      this.lastName = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCompanyName() {
      return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCompanyName(String value) {
      this.companyName = value;
    }

  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="subscription_id" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="invoice_number" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *         &lt;element name="po_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="vat_number" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="total_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="date">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="closed_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="net_terms" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *         &lt;element name="collection_method" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *       &lt;/sequence>
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "uuid", "subscriptionId", "state", "invoiceNumber", "poNumber", "vatNumber",
      "totalInCents", "currency", "date", "closedAt", "netTerms", "collectionMethod" })
  public static class Invoice {

    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(name = "subscription_id", required = true)
    protected String subscriptionId;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(name = "invoice_number")
    protected short invoiceNumber;
    @XmlElement(name = "po_number", required = true)
    protected String poNumber;
    @XmlElement(name = "vat_number", required = true)
    protected String vatNumber;
    @XmlElement(name = "total_in_cents")
    protected short totalInCents;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected NewInvoiceNotification.Invoice.Date date;
    @XmlElement(name = "closed_at", required = true)
    protected NewInvoiceNotification.Invoice.ClosedAt closedAt;
    @XmlElement(name = "net_terms")
    protected byte netTerms;
    @XmlElement(name = "collection_method", required = true)
    protected String collectionMethod;

    /**
     * Gets the value of the uuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUuid() {
      return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setUuid(String value) {
      this.uuid = value;
    }

    /**
     * Gets the value of the subscriptionId property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getSubscriptionId() {
      return subscriptionId;
    }

    /**
     * Sets the value of the subscriptionId property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setSubscriptionId(String value) {
      this.subscriptionId = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
      return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setState(String value) {
      this.state = value;
    }

    /**
     * Gets the value of the invoiceNumber property.
     * 
     */
    public short getInvoiceNumber() {
      return invoiceNumber;
    }

    /**
     * Sets the value of the invoiceNumber property.
     * 
     */
    public void setInvoiceNumber(short value) {
      this.invoiceNumber = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getPoNumber() {
      return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setPoNumber(String value) {
      this.poNumber = value;
    }

    /**
     * Gets the value of the vatNumber property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getVatNumber() {
      return vatNumber;
    }

    /**
     * Sets the value of the vatNumber property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setVatNumber(String value) {
      this.vatNumber = value;
    }

    /**
     * Gets the value of the totalInCents property.
     * 
     */
    public short getTotalInCents() {
      return totalInCents;
    }

    /**
     * Sets the value of the totalInCents property.
     * 
     */
    public void setTotalInCents(short value) {
      this.totalInCents = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
      return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
      this.currency = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return possible object is {@link NewInvoiceNotification.Invoice.Date }
     * 
     */
    public NewInvoiceNotification.Invoice.Date getDate() {
      return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *          allowed object is {@link NewInvoiceNotification.Invoice.Date }
     * 
     */
    public void setDate(NewInvoiceNotification.Invoice.Date value) {
      this.date = value;
    }

    /**
     * Gets the value of the closedAt property.
     * 
     * @return possible object is {@link NewInvoiceNotification.Invoice.ClosedAt }
     * 
     */
    public NewInvoiceNotification.Invoice.ClosedAt getClosedAt() {
      return closedAt;
    }

    /**
     * Sets the value of the closedAt property.
     * 
     * @param value
     *          allowed object is {@link NewInvoiceNotification.Invoice.ClosedAt }
     * 
     */
    public void setClosedAt(NewInvoiceNotification.Invoice.ClosedAt value) {
      this.closedAt = value;
    }

    /**
     * Gets the value of the netTerms property.
     * 
     */
    public byte getNetTerms() {
      return netTerms;
    }

    /**
     * Sets the value of the netTerms property.
     * 
     */
    public void setNetTerms(byte value) {
      this.netTerms = value;
    }

    /**
     * Gets the value of the collectionMethod property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCollectionMethod() {
      return collectionMethod;
    }

    /**
     * Sets the value of the collectionMethod property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCollectionMethod(String value) {
      this.collectionMethod = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="nil" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class ClosedAt {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "type")
      protected String type;
      @XmlAttribute(name = "nil")
      protected String nil;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

      /**
       * Gets the value of the nil property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getNil() {
        return nil;
      }

      /**
       * Sets the value of the nil property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setNil(String value) {
        this.nil = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Date {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

  }

}
