//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.11.26 at 01:56:42 AM PST
//

package com.sciul.recurly.model;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * @author Gaurav
 */
/**
 * This object contains factory methods for each Java content interface and Java element interface generated in the
 * generated package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the Java representation for XML content.
 * The Java representation of XML content can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory methods for each of these are provided in
 * this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package:
   * generated
   * 
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link Accounts }
   * 
   */
  public Accounts createAccounts() {
    return new Accounts();
  }

  /**
   * Create an instance of {@link Accounts.Account }
   * 
   */
  public Accounts.Account createAccountsAccount() {
    return new Accounts.Account();
  }

  /**
   * Create an instance of {@link Accounts.Account.Address }
   * 
   */
  public Accounts.Account.Address createAccountsAccountAddress() {
    return new Accounts.Account.Address();
  }

  /**
   * Create an instance of {@link Accounts.Account.Adjustments }
   * 
   */
  public Accounts.Account.Adjustments createAccountsAccountAdjustments() {
    return new Accounts.Account.Adjustments();
  }

  /**
   * Create an instance of {@link Accounts.Account.BillingInfo }
   * 
   */
  public Accounts.Account.BillingInfo createAccountsAccountBillingInfo() {
    return new Accounts.Account.BillingInfo();
  }

  /**
   * Create an instance of {@link Accounts.Account.Invoices }
   * 
   */
  public Accounts.Account.Invoices createAccountsAccountInvoices() {
    return new Accounts.Account.Invoices();
  }

  /**
   * Create an instance of {@link Accounts.Account.Redemption }
   * 
   */
  public Accounts.Account.Redemption createAccountsAccountRedemption() {
    return new Accounts.Account.Redemption();
  }

  /**
   * Create an instance of {@link Accounts.Account.Subscriptions }
   * 
   */
  public Accounts.Account.Subscriptions createAccountsAccountSubscriptions() {
    return new Accounts.Account.Subscriptions();
  }

  /**
   * Create an instance of {@link Accounts.Account.Transactions }
   * 
   */
  public Accounts.Account.Transactions createAccountsAccountTransactions() {
    return new Accounts.Account.Transactions();
  }

  /**
   * Create an instance of {@link Accounts.Account.Username }
   * 
   */
  public Accounts.Account.Username createAccountsAccountUsername() {
    return new Accounts.Account.Username();
  }

  /**
   * Create an instance of {@link Accounts.Account.VatNumber }
   * 
   */
  public Accounts.Account.VatNumber createAccountsAccountVatNumber() {
    return new Accounts.Account.VatNumber();
  }

  /**
   * Create an instance of {@link Accounts.Account.TaxExempt }
   * 
   */
  public Accounts.Account.TaxExempt createAccountsAccountTaxExempt() {
    return new Accounts.Account.TaxExempt();
  }

  /**
   * Create an instance of {@link Accounts.Account.AcceptLanguage }
   * 
   */
  public Accounts.Account.AcceptLanguage createAccountsAccountAcceptLanguage() {
    return new Accounts.Account.AcceptLanguage();
  }

  /**
   * Create an instance of {@link Accounts.Account.CreatedAt }
   * 
   */
  public Accounts.Account.CreatedAt createAccountsAccountCreatedAt() {
    return new Accounts.Account.CreatedAt();
  }

  /**
   * Create an instance of {@link Accounts.Account.Address.Address2 }
   * 
   */
  public Accounts.Account.Address.Address2 createAccountsAccountAddressAddress2() {
    return new Accounts.Account.Address.Address2();
  }

  /**
   * Create an instance of {@link Accounts.Account.Address.Phone }
   * 
   */
  public Accounts.Account.Address.Phone createAccountsAccountAddressPhone() {
    return new Accounts.Account.Address.Phone();
  }

  /**
   * Create an instance of {@link Plans }
   * 
   */
  public Plans createPlans() {
    return new Plans();
  }

  /**
   * Create an instance of {@link Plans.Plan }
   * 
   */
  public Plans.Plan createPlansPlan() {
    return new Plans.Plan();
  }

  /**
   * Create an instance of {@link Plans.Plan.SetupFeeInCents }
   * 
   */
  public Plans.Plan.SetupFeeInCents createPlansPlanSetupFeeInCents() {
    return new Plans.Plan.SetupFeeInCents();
  }

  /**
   * Create an instance of {@link Plans.Plan.UnitAmountInCents }
   * 
   */
  public Plans.Plan.UnitAmountInCents createPlansPlanUnitAmountInCents() {
    return new Plans.Plan.UnitAmountInCents();
  }

  /**
   * Create an instance of {@link Plans.Plan.AddOns }
   * 
   */
  public Plans.Plan.AddOns createPlansPlanAddOns() {
    return new Plans.Plan.AddOns();
  }

  /**
   * Create an instance of {@link Plans.Plan.Description }
   * 
   */
  public Plans.Plan.Description createPlansPlanDescription() {
    return new Plans.Plan.Description();
  }

  /**
   * Create an instance of {@link Plans.Plan.SuccessUrl }
   * 
   */
  public Plans.Plan.SuccessUrl createPlansPlanSuccessUrl() {
    return new Plans.Plan.SuccessUrl();
  }

  /**
   * Create an instance of {@link Plans.Plan.CancelUrl }
   * 
   */
  public Plans.Plan.CancelUrl createPlansPlanCancelUrl() {
    return new Plans.Plan.CancelUrl();
  }

  /**
   * Create an instance of {@link Plans.Plan.DisplayDonationAmounts }
   * 
   */
  public Plans.Plan.DisplayDonationAmounts createPlansPlanDisplayDonationAmounts() {
    return new Plans.Plan.DisplayDonationAmounts();
  }

  /**
   * Create an instance of {@link Plans.Plan.DisplayQuantity }
   * 
   */
  public Plans.Plan.DisplayQuantity createPlansPlanDisplayQuantity() {
    return new Plans.Plan.DisplayQuantity();
  }

  /**
   * Create an instance of {@link Plans.Plan.DisplayPhoneNumber }
   * 
   */
  public Plans.Plan.DisplayPhoneNumber createPlansPlanDisplayPhoneNumber() {
    return new Plans.Plan.DisplayPhoneNumber();
  }

  /**
   * Create an instance of {@link Plans.Plan.BypassHostedConfirmation }
   * 
   */
  public Plans.Plan.BypassHostedConfirmation createPlansPlanBypassHostedConfirmation() {
    return new Plans.Plan.BypassHostedConfirmation();
  }

  /**
   * Create an instance of {@link Plans.Plan.PaymentPageTosLink }
   * 
   */
  public Plans.Plan.PaymentPageTosLink createPlansPlanPaymentPageTosLink() {
    return new Plans.Plan.PaymentPageTosLink();
  }

  /**
   * Create an instance of {@link Plans.Plan.PlanIntervalLength }
   * 
   */
  public Plans.Plan.PlanIntervalLength createPlansPlanPlanIntervalLength() {
    return new Plans.Plan.PlanIntervalLength();
  }

  /**
   * Create an instance of {@link Plans.Plan.TrialIntervalLength }
   * 
   */
  public Plans.Plan.TrialIntervalLength createPlansPlanTrialIntervalLength() {
    return new Plans.Plan.TrialIntervalLength();
  }

  /**
   * Create an instance of {@link Plans.Plan.AccountingCode }
   * 
   */
  public Plans.Plan.AccountingCode createPlansPlanAccountingCode() {
    return new Plans.Plan.AccountingCode();
  }

  /**
   * Create an instance of {@link Plans.Plan.CreatedAt }
   * 
   */
  public Plans.Plan.CreatedAt createPlansPlanCreatedAt() {
    return new Plans.Plan.CreatedAt();
  }

  /**
   * Create an instance of {@link Plans.Plan.TaxExempt }
   * 
   */
  public Plans.Plan.TaxExempt createPlansPlanTaxExempt() {
    return new Plans.Plan.TaxExempt();
  }

  /**
   * Create an instance of {@link Plans.Plan.SetupFeeInCents.USD }
   * 
   */
  public Plans.Plan.SetupFeeInCents.USD createPlansPlanSetupFeeInCentsUSD() {
    return new Plans.Plan.SetupFeeInCents.USD();
  }

  /**
   * Create an instance of {@link Plans.Plan.SetupFeeInCents.EUR }
   * 
   */
  public Plans.Plan.SetupFeeInCents.EUR createPlansPlanSetupFeeInCentsEUR() {
    return new Plans.Plan.SetupFeeInCents.EUR();
  }

  /**
   * Create an instance of {@link Plans.Plan.UnitAmountInCents.USD }
   * 
   */
  public Plans.Plan.UnitAmountInCents.USD createPlansPlanUnitAmountInCentsUSD() {
    return new Plans.Plan.UnitAmountInCents.USD();
  }

  /**
   * Create an instance of {@link Plans.Plan.UnitAmountInCents.EUR }
   * 
   */
  public Plans.Plan.UnitAmountInCents.EUR createPlansPlanUnitAmountInCentsEUR() {
    return new Plans.Plan.UnitAmountInCents.EUR();
  }

}
