//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.12.06 at 11:50:05 PM PST
//

package com.sciul.recurly.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="subscription">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="account">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="invoice">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="plan">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="plan_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="unit_amount_in_cents">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="quantity">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="activated_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="canceled_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="expires_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="current_period_started_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="current_period_ends_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="trial_started_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="trial_ends_at">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tax_in_cents">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="tax_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tax_region" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="tax_rate">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="po_number">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="net_terms">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
 *                           &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="subscription_add_ons">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="subscription_add_on" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="add_on_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="unit_amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="a" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "subscription" })
@XmlRootElement(name = "subscriptions")
public class Subscriptions {

  @XmlElement(required = true)
  protected Subscriptions.Subscription subscription;
  @XmlAttribute(name = "type")
  protected String type;

  /**
   * Gets the value of the subscription property.
   * 
   * @return possible object is {@link Subscriptions.Subscription }
   * 
   */
  public Subscriptions.Subscription getSubscription() {
    return subscription;
  }

  /**
   * Sets the value of the subscription property.
   * 
   * @param value
   *          allowed object is {@link Subscriptions.Subscription }
   * 
   */
  public void setSubscription(Subscriptions.Subscription value) {
    this.subscription = value;
  }

  /**
   * Gets the value of the type property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getType() {
    return type;
  }

  /**
   * Sets the value of the type property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setType(String value) {
    this.type = value;
  }

  /**
   * <p>
   * Java class for anonymous complex type.
   * 
   * <p>
   * The following schema fragment specifies the expected content contained within this class.
   * 
   * <pre>
   * &lt;complexType>
   *   &lt;complexContent>
   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *       &lt;sequence>
   *         &lt;element name="account">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="invoice">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="plan">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="plan_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                 &lt;/sequence>
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="uuid" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="state" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="unit_amount_in_cents">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="currency" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="quantity">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="activated_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="canceled_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="expires_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="current_period_started_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="current_period_ends_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="trial_started_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="trial_ends_at">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="tax_in_cents">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="tax_type" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="tax_region" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *         &lt;element name="tax_rate">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="po_number">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="net_terms">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
   *                 &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="subscription_add_ons">
   *           &lt;complexType>
   *             &lt;complexContent>
   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                 &lt;sequence>
   *                   &lt;element name="subscription_add_on" maxOccurs="unbounded" minOccurs="0">
   *                     &lt;complexType>
   *                       &lt;complexContent>
   *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
   *                           &lt;sequence>
   *                             &lt;element name="add_on_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
   *                             &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
   *                             &lt;element name="unit_amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
   *                           &lt;/sequence>
   *                         &lt;/restriction>
   *                       &lt;/complexContent>
   *                     &lt;/complexType>
   *                   &lt;/element>
   *                 &lt;/sequence>
   *               &lt;/restriction>
   *             &lt;/complexContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *         &lt;element name="a" maxOccurs="unbounded" minOccurs="0">
   *           &lt;complexType>
   *             &lt;simpleContent>
   *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
   *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *                 &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
   *               &lt;/extension>
   *             &lt;/simpleContent>
   *           &lt;/complexType>
   *         &lt;/element>
   *       &lt;/sequence>
   *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
   *     &lt;/restriction>
   *   &lt;/complexContent>
   * &lt;/complexType>
   * </pre>
   * 
   * 
   */
  @XmlAccessorType(XmlAccessType.FIELD)
  @XmlType(name = "", propOrder = { "account", "invoice", "plan", "uuid", "state", "unitAmountInCents", "currency",
      "quantity", "activatedAt", "canceledAt", "expiresAt", "currentPeriodStartedAt", "currentPeriodEndsAt",
      "trialStartedAt", "trialEndsAt", "taxInCents", "taxType", "taxRegion", "taxRate", "poNumber", "netTerms",
      "subscriptionAddOns", "a" })
  public static class Subscription {

    @XmlElement(required = true)
    protected Subscriptions.Subscription.Account account;
    @XmlElement(required = true)
    protected Subscriptions.Subscription.Invoice invoice;
    @XmlElement(required = true)
    protected Subscriptions.Subscription.Plan plan;
    @XmlElement(required = true)
    protected String uuid;
    @XmlElement(required = true)
    protected String state;
    @XmlElement(name = "unit_amount_in_cents", required = true)
    protected Subscriptions.Subscription.UnitAmountInCents unitAmountInCents;
    @XmlElement(required = true)
    protected String currency;
    @XmlElement(required = true)
    protected Subscriptions.Subscription.Quantity quantity;
    @XmlElement(name = "activated_at", required = true)
    protected Subscriptions.Subscription.ActivatedAt activatedAt;
    @XmlElement(name = "canceled_at", required = true)
    protected Subscriptions.Subscription.CanceledAt canceledAt;
    @XmlElement(name = "expires_at", required = true)
    protected Subscriptions.Subscription.ExpiresAt expiresAt;
    @XmlElement(name = "current_period_started_at", required = true)
    protected Subscriptions.Subscription.CurrentPeriodStartedAt currentPeriodStartedAt;
    @XmlElement(name = "current_period_ends_at", required = true)
    protected Subscriptions.Subscription.CurrentPeriodEndsAt currentPeriodEndsAt;
    @XmlElement(name = "trial_started_at", required = true)
    protected Subscriptions.Subscription.TrialStartedAt trialStartedAt;
    @XmlElement(name = "trial_ends_at", required = true)
    protected Subscriptions.Subscription.TrialEndsAt trialEndsAt;
    @XmlElement(name = "tax_in_cents", required = true)
    protected Subscriptions.Subscription.TaxInCents taxInCents;
    @XmlElement(name = "tax_type", required = true)
    protected String taxType;
    @XmlElement(name = "tax_region", required = true)
    protected String taxRegion;
    @XmlElement(name = "tax_rate", required = true)
    protected Subscriptions.Subscription.TaxRate taxRate;
    @XmlElement(name = "po_number", required = true)
    protected Subscriptions.Subscription.PoNumber poNumber;
    @XmlElement(name = "net_terms", required = true)
    protected Subscriptions.Subscription.NetTerms netTerms;
    @XmlElement(name = "subscription_add_ons", required = true)
    protected Subscriptions.Subscription.SubscriptionAddOns subscriptionAddOns;
    protected List<Subscriptions.Subscription.A> a;
    @XmlAttribute(name = "href")
    protected String href;

    /**
     * Gets the value of the account property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.Account }
     * 
     */
    public Subscriptions.Subscription.Account getAccount() {
      return account;
    }

    /**
     * Sets the value of the account property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.Account }
     * 
     */
    public void setAccount(Subscriptions.Subscription.Account value) {
      this.account = value;
    }

    /**
     * Gets the value of the invoice property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.Invoice }
     * 
     */
    public Subscriptions.Subscription.Invoice getInvoice() {
      return invoice;
    }

    /**
     * Sets the value of the invoice property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.Invoice }
     * 
     */
    public void setInvoice(Subscriptions.Subscription.Invoice value) {
      this.invoice = value;
    }

    /**
     * Gets the value of the plan property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.Plan }
     * 
     */
    public Subscriptions.Subscription.Plan getPlan() {
      return plan;
    }

    /**
     * Sets the value of the plan property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.Plan }
     * 
     */
    public void setPlan(Subscriptions.Subscription.Plan value) {
      this.plan = value;
    }

    /**
     * Gets the value of the uuid property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getUuid() {
      return uuid;
    }

    /**
     * Sets the value of the uuid property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setUuid(String value) {
      this.uuid = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getState() {
      return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setState(String value) {
      this.state = value;
    }

    /**
     * Gets the value of the unitAmountInCents property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.UnitAmountInCents }
     * 
     */
    public Subscriptions.Subscription.UnitAmountInCents getUnitAmountInCents() {
      return unitAmountInCents;
    }

    /**
     * Sets the value of the unitAmountInCents property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.UnitAmountInCents }
     * 
     */
    public void setUnitAmountInCents(Subscriptions.Subscription.UnitAmountInCents value) {
      this.unitAmountInCents = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getCurrency() {
      return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setCurrency(String value) {
      this.currency = value;
    }

    /**
     * Gets the value of the quantity property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.Quantity }
     * 
     */
    public Subscriptions.Subscription.Quantity getQuantity() {
      return quantity;
    }

    /**
     * Sets the value of the quantity property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.Quantity }
     * 
     */
    public void setQuantity(Subscriptions.Subscription.Quantity value) {
      this.quantity = value;
    }

    /**
     * Gets the value of the activatedAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.ActivatedAt }
     * 
     */
    public Subscriptions.Subscription.ActivatedAt getActivatedAt() {
      return activatedAt;
    }

    /**
     * Sets the value of the activatedAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.ActivatedAt }
     * 
     */
    public void setActivatedAt(Subscriptions.Subscription.ActivatedAt value) {
      this.activatedAt = value;
    }

    /**
     * Gets the value of the canceledAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.CanceledAt }
     * 
     */
    public Subscriptions.Subscription.CanceledAt getCanceledAt() {
      return canceledAt;
    }

    /**
     * Sets the value of the canceledAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.CanceledAt }
     * 
     */
    public void setCanceledAt(Subscriptions.Subscription.CanceledAt value) {
      this.canceledAt = value;
    }

    /**
     * Gets the value of the expiresAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.ExpiresAt }
     * 
     */
    public Subscriptions.Subscription.ExpiresAt getExpiresAt() {
      return expiresAt;
    }

    /**
     * Sets the value of the expiresAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.ExpiresAt }
     * 
     */
    public void setExpiresAt(Subscriptions.Subscription.ExpiresAt value) {
      this.expiresAt = value;
    }

    /**
     * Gets the value of the currentPeriodStartedAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.CurrentPeriodStartedAt }
     * 
     */
    public Subscriptions.Subscription.CurrentPeriodStartedAt getCurrentPeriodStartedAt() {
      return currentPeriodStartedAt;
    }

    /**
     * Sets the value of the currentPeriodStartedAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.CurrentPeriodStartedAt }
     * 
     */
    public void setCurrentPeriodStartedAt(Subscriptions.Subscription.CurrentPeriodStartedAt value) {
      this.currentPeriodStartedAt = value;
    }

    /**
     * Gets the value of the currentPeriodEndsAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.CurrentPeriodEndsAt }
     * 
     */
    public Subscriptions.Subscription.CurrentPeriodEndsAt getCurrentPeriodEndsAt() {
      return currentPeriodEndsAt;
    }

    /**
     * Sets the value of the currentPeriodEndsAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.CurrentPeriodEndsAt }
     * 
     */
    public void setCurrentPeriodEndsAt(Subscriptions.Subscription.CurrentPeriodEndsAt value) {
      this.currentPeriodEndsAt = value;
    }

    /**
     * Gets the value of the trialStartedAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.TrialStartedAt }
     * 
     */
    public Subscriptions.Subscription.TrialStartedAt getTrialStartedAt() {
      return trialStartedAt;
    }

    /**
     * Sets the value of the trialStartedAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.TrialStartedAt }
     * 
     */
    public void setTrialStartedAt(Subscriptions.Subscription.TrialStartedAt value) {
      this.trialStartedAt = value;
    }

    /**
     * Gets the value of the trialEndsAt property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.TrialEndsAt }
     * 
     */
    public Subscriptions.Subscription.TrialEndsAt getTrialEndsAt() {
      return trialEndsAt;
    }

    /**
     * Sets the value of the trialEndsAt property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.TrialEndsAt }
     * 
     */
    public void setTrialEndsAt(Subscriptions.Subscription.TrialEndsAt value) {
      this.trialEndsAt = value;
    }

    /**
     * Gets the value of the taxInCents property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.TaxInCents }
     * 
     */
    public Subscriptions.Subscription.TaxInCents getTaxInCents() {
      return taxInCents;
    }

    /**
     * Sets the value of the taxInCents property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.TaxInCents }
     * 
     */
    public void setTaxInCents(Subscriptions.Subscription.TaxInCents value) {
      this.taxInCents = value;
    }

    /**
     * Gets the value of the taxType property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxType() {
      return taxType;
    }

    /**
     * Sets the value of the taxType property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setTaxType(String value) {
      this.taxType = value;
    }

    /**
     * Gets the value of the taxRegion property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getTaxRegion() {
      return taxRegion;
    }

    /**
     * Sets the value of the taxRegion property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setTaxRegion(String value) {
      this.taxRegion = value;
    }

    /**
     * Gets the value of the taxRate property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.TaxRate }
     * 
     */
    public Subscriptions.Subscription.TaxRate getTaxRate() {
      return taxRate;
    }

    /**
     * Sets the value of the taxRate property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.TaxRate }
     * 
     */
    public void setTaxRate(Subscriptions.Subscription.TaxRate value) {
      this.taxRate = value;
    }

    /**
     * Gets the value of the poNumber property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.PoNumber }
     * 
     */
    public Subscriptions.Subscription.PoNumber getPoNumber() {
      return poNumber;
    }

    /**
     * Sets the value of the poNumber property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.PoNumber }
     * 
     */
    public void setPoNumber(Subscriptions.Subscription.PoNumber value) {
      this.poNumber = value;
    }

    /**
     * Gets the value of the netTerms property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.NetTerms }
     * 
     */
    public Subscriptions.Subscription.NetTerms getNetTerms() {
      return netTerms;
    }

    /**
     * Sets the value of the netTerms property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.NetTerms }
     * 
     */
    public void setNetTerms(Subscriptions.Subscription.NetTerms value) {
      this.netTerms = value;
    }

    /**
     * Gets the value of the subscriptionAddOns property.
     * 
     * @return possible object is {@link Subscriptions.Subscription.SubscriptionAddOns }
     * 
     */
    public Subscriptions.Subscription.SubscriptionAddOns getSubscriptionAddOns() {
      return subscriptionAddOns;
    }

    /**
     * Sets the value of the subscriptionAddOns property.
     * 
     * @param value
     *          allowed object is {@link Subscriptions.Subscription.SubscriptionAddOns }
     * 
     */
    public void setSubscriptionAddOns(Subscriptions.Subscription.SubscriptionAddOns value) {
      this.subscriptionAddOns = value;
    }

    /**
     * Gets the value of the a property.
     * 
     * <p>
     * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make to
     * the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method for
     * the a property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * 
     * <pre>
     * getA().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list {@link Subscriptions.Subscription.A }
     * 
     * 
     */
    public List<Subscriptions.Subscription.A> getA() {
      if (a == null) {
        a = new ArrayList<Subscriptions.Subscription.A>();
      }
      return this.a;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return possible object is {@link String }
     * 
     */
    public String getHref() {
      return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *          allowed object is {@link String }
     * 
     */
    public void setHref(String value) {
      this.href = value;
    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="method" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class A {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "name")
      protected String name;
      @XmlAttribute(name = "href")
      protected String href;
      @XmlAttribute(name = "method")
      protected String method;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the name property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

      /**
       * Gets the value of the method property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getMethod() {
        return method;
      }

      /**
       * Sets the value of the method property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setMethod(String value) {
        this.method = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Account {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class ActivatedAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CanceledAt {

      @XmlValue
      protected String value;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CurrentPeriodEndsAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>dateTime">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class CurrentPeriodStartedAt {

      @XmlValue
      @XmlSchemaType(name = "dateTime")
      protected XMLGregorianCalendar value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link XMLGregorianCalendar }
       * 
       */
      public XMLGregorianCalendar getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link XMLGregorianCalendar }
       * 
       */
      public void setValue(XMLGregorianCalendar value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class ExpiresAt {

      @XmlValue
      protected String value;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Invoice {

      @XmlValue
      protected String value;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class NetTerms {

      @XmlValue
      protected byte value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       */
      public byte getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       */
      public void setValue(byte value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="plan_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="href" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "planCode", "name" })
    public static class Plan {

      @XmlElement(name = "plan_code", required = true)
      protected String planCode;
      @XmlElement(required = true)
      protected String name;
      @XmlAttribute(name = "href")
      protected String href;

      /**
       * Gets the value of the planCode property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getPlanCode() {
        return planCode;
      }

      /**
       * Sets the value of the planCode property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setPlanCode(String value) {
        this.planCode = value;
      }

      /**
       * Gets the value of the name property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getName() {
        return name;
      }

      /**
       * Sets the value of the name property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setName(String value) {
        this.name = value;
      }

      /**
       * Gets the value of the href property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getHref() {
        return href;
      }

      /**
       * Sets the value of the href property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setHref(String value) {
        this.href = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class PoNumber {

      @XmlValue
      protected String value;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class Quantity {

      @XmlValue
      protected byte value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       */
      public byte getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       */
      public void setValue(byte value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="subscription_add_on" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="add_on_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                   &lt;element name="unit_amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "subscriptionAddOn" })
    public static class SubscriptionAddOns {

      @XmlElement(name = "subscription_add_on")
      protected List<Subscriptions.Subscription.SubscriptionAddOns.SubscriptionAddOn> subscriptionAddOn;

      /**
       * Gets the value of the subscriptionAddOn property.
       * 
       * <p>
       * This accessor method returns a reference to the live list, not a snapshot. Therefore any modification you make
       * to the returned list will be present inside the JAXB object. This is why there is not a <CODE>set</CODE> method
       * for the subscriptionAddOn property.
       * 
       * <p>
       * For example, to add a new item, do as follows:
       * 
       * <pre>
       * getSubscriptionAddOn().add(newItem);
       * </pre>
       * 
       * 
       * <p>
       * Objects of the following type(s) are allowed in the list
       * {@link Subscriptions.Subscription.SubscriptionAddOns.SubscriptionAddOn }
       * 
       * 
       */
      public List<Subscriptions.Subscription.SubscriptionAddOns.SubscriptionAddOn> getSubscriptionAddOn() {
        if (subscriptionAddOn == null) {
          subscriptionAddOn = new ArrayList<Subscriptions.Subscription.SubscriptionAddOns.SubscriptionAddOn>();
        }
        return this.subscriptionAddOn;
      }

      /**
       * <p>
       * Java class for anonymous complex type.
       * 
       * <p>
       * The following schema fragment specifies the expected content contained within this class.
       * 
       * <pre>
       * &lt;complexType>
       *   &lt;complexContent>
       *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
       *       &lt;sequence>
       *         &lt;element name="add_on_code" type="{http://www.w3.org/2001/XMLSchema}string"/>
       *         &lt;element name="quantity" type="{http://www.w3.org/2001/XMLSchema}byte"/>
       *         &lt;element name="unit_amount_in_cents" type="{http://www.w3.org/2001/XMLSchema}short"/>
       *       &lt;/sequence>
       *     &lt;/restriction>
       *   &lt;/complexContent>
       * &lt;/complexType>
       * </pre>
       * 
       * 
       */
      @XmlAccessorType(XmlAccessType.FIELD)
      @XmlType(name = "", propOrder = { "addOnCode", "quantity", "unitAmountInCents" })
      public static class SubscriptionAddOn {

        @XmlElement(name = "add_on_code", required = true)
        protected String addOnCode;
        protected byte quantity;
        @XmlElement(name = "unit_amount_in_cents")
        protected short unitAmountInCents;

        /**
         * Gets the value of the addOnCode property.
         * 
         * @return possible object is {@link String }
         * 
         */
        public String getAddOnCode() {
          return addOnCode;
        }

        /**
         * Sets the value of the addOnCode property.
         * 
         * @param value
         *          allowed object is {@link String }
         * 
         */
        public void setAddOnCode(String value) {
          this.addOnCode = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public byte getQuantity() {
          return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQuantity(byte value) {
          this.quantity = value;
        }

        /**
         * Gets the value of the unitAmountInCents property.
         * 
         */
        public short getUnitAmountInCents() {
          return unitAmountInCents;
        }

        /**
         * Sets the value of the unitAmountInCents property.
         * 
         */
        public void setUnitAmountInCents(short value) {
          this.unitAmountInCents = value;
        }

      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>byte">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class TaxInCents {

      @XmlValue
      protected byte value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       */
      public byte getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       */
      public void setValue(byte value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class TaxRate {

      @XmlValue
      protected float value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       */
      public float getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       */
      public void setValue(float value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class TrialEndsAt {

      @XmlValue
      protected String value;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class TrialStartedAt {

      @XmlValue
      protected String value;

      /**
       * Gets the value of the value property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setValue(String value) {
        this.value = value;
      }

    }

    /**
     * <p>
     * Java class for anonymous complex type.
     * 
     * <p>
     * The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>short">
     *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = { "value" })
    public static class UnitAmountInCents {

      @XmlValue
      protected short value;
      @XmlAttribute(name = "type")
      protected String type;

      /**
       * Gets the value of the value property.
       * 
       */
      public short getValue() {
        return value;
      }

      /**
       * Sets the value of the value property.
       * 
       */
      public void setValue(short value) {
        this.value = value;
      }

      /**
       * Gets the value of the type property.
       * 
       * @return possible object is {@link String }
       * 
       */
      public String getType() {
        return type;
      }

      /**
       * Sets the value of the type property.
       * 
       * @param value
       *          allowed object is {@link String }
       * 
       */
      public void setType(String value) {
        this.type = value;
      }

    }

  }

}
